name: esp32_cam_app
description: A beautiful app to receive and save photos from an ESP32-CAM.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  path: ^1.8.3
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
